#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Takumi Kobayashi
# SPDX-License-Identifier: BSD-3-Clause

import sys
from datetime import datetime

def save(memo):
    file = open("memo.txt", "a")
    timestamp = datetime.now().strftime("[%Y-%m-%d %H:%M:%S]")
    file.write(f"{timestamp} {memo}\n")
    file.close

def display():
    print("=== メモ一覧 ===")
    try:
        file = open("memo.txt", "r")
        print(file.read())
        file.close()
    except FileNotFoundError:
        print("まだメモはないよ!")

def main():
    input_data = sys.stdin.read().strip()

    if not input_data:
        print("エラー: 空のメモは保存出来ない！", file=sys.stderr)
        sys.exit(1)

    if input_data == "list":
        display()

    else:
        save(input_data)

if __name__ == "__main__":
    main()
  
