#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Takumi Kobayashi
# SPDX-License-Identifier: BSD-3-Clause

import sys
from datetime import datetime

def save(memo):
    file = open("memo.txt", "a")
    timestamp = datetime.now().strftime("[%Y-%m-%d %H:%M:%S]")
    file.write(f"{timestamp} {memo}\n")
    file.close()
    print("メモを保存！")

def display():
    print("=== メモ一覧 ===")
    try:
        file = open("memo.txt", "r")
        print(file.read())
        file.close()
    except FileNotFoundError:
        print("まだはメモはないよ!")

if sys.argv[1:]:
    memo = "".join(sys.argv[1:]).strip()
    if not memo:
        print("エラー: 空のメモは保存出来ない！", file=sys.stderr)
        sys.exit(1)

    save(memo)

else:
    display()
